# Generated by Django 4.2.8 on 2024-01-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="improvement",
            field=models.TextField(default="temp"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedback",
            name="strength",
            field=models.TextField(default="temp"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedback",
            name="weakness",
            field=models.TextField(default="temp"),
            preserve_default=False,
        ),
    ]
